### ISSUE TITLE
impossible to unregister Singleton

### ISSUE THREAD

**Issue by fullflash** [fluttercommunity/get_it#270]
Hi.
unregister method seems only support factory objects not singletons.

is there a way to unregister singleton instances from get_it.

```
Object[/factory]() with  type BuylistBloc is not registered inside GetIt.
(Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
Did you forget to register it?)
'package:get_it[/get_it_impl.dart]()':
package:get_it/get_it_impl.dart:1
Failed assertion: line 372 pos 7: 'instanceFactory != null'
#0      _AssertionError._doThrowNew (dart:core-patch[/errors_patch.dart:51:61]())
#1      _AssertionError._throwNew (dart:core-patch[/errors_patch.dart:40:5]())
#2      _GetItImplementation._findFactoryByNameAndType
package:get_it/get_it_impl.dart:372
#3      _GetItImplementation.get
package:get_it/get_it_impl.dart:393
#4      _GetItImplementation.call
package:get_it/get_it_impl.dart:430
```

**Comment by fullflash** [comment]
the error happens if you do register without generic.

must registerSingleton instances providing class type as generic.
