### ISSUE TITLE
Seemingly unable to register dependent singleton

### ISSUE THREAD

**Issue by FluffyDiscord** [fluttercommunity/get_it#396]
I am confused why GetIt cannot find `Storage` when it's trying to register `HttpClient`. What I am doing wrong? I do call `GetIt.I.signalReady(this)` in my `Storage` once it's done initializing.

```dart
Future registerDI() async {
  GetIt.I.registerSingleton<Storage>(
    Storage(),
    signalsReady: true,
  );

  await GetIt.I.isReady<Storage>();

  GetIt.I.registerSingleton<HttpClient>(
    HttpClient(GetIt.I<Storage>()),
    signalsReady: true,
  );

  return GetIt.I.allReady();
}
```

Error message
```
/flutter ( 6937): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: This instance of the type HttpClient is not available in GetIt If you have registered it as LazySingleton, are you sure you have used it at least once?
E/flutter ( 6937): #0      throwIf (package:get_it/get_it_impl.dart:9:18)
E/flutter ( 6937): #1      _GetItImplementation._findFactoryByInstance (package:get_it/get_it_impl.dart:1291:5)
E/flutter ( 6937): #2      _GetItImplementation.signalReady (package:get_it/get_it_impl.dart:1822:28)
E/flutter ( 6937): #3      new HttpClient (package:m/http/http_client.dart:47:13)
```

**Comment by FluffyDiscord** [comment]
My bad, can't read....

**Comment by escamoteur** [comment]
Check my blog post
https://blog.burkharts.net/lets-get-this-party-started-startup-orchestration-with-getit
Am 20. Dez. 2024, 23:45 +0100 schrieb Honk ***@***.***>:
